// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Eh6e3dODxK6QcsqziplsLxIIF1bjUBs',
    appId: '1:926551021783:web:00b6dfa6c0c4ff8c35b892',
    messagingSenderId: '926551021783',
    projectId: 'whatsapp-clone-8f1b0',
    authDomain: 'whatsapp-clone-8f1b0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-8f1b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-ovEPPuldlQTbXpJ10TNR6FrAoWjTXg',
    appId: '1:926551021783:android:3c6e3db2410c171035b892',
    messagingSenderId: '926551021783',
    projectId: 'whatsapp-clone-8f1b0',
    storageBucket: 'whatsapp-clone-8f1b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN39tT02NwQcoAIwG-QDsgxEy8iwoPVZk',
    appId: '1:926551021783:ios:43d57cb428ab3a8f35b892',
    messagingSenderId: '926551021783',
    projectId: 'whatsapp-clone-8f1b0',
    storageBucket: 'whatsapp-clone-8f1b0.appspot.com',
    iosBundleId: 'com.example.whatsappCloneWoc',
  );
}
